version: '3.9'
services:
  svelte-commerce:
    build:
      dockerfile: Dockerfile
      context: .
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - APP_VERSION="1.0.1"
      # Add this line to use .env instead of .env.example
      - ENV_FILE=.env